### ISSUE TITLE
Problems with FastAPI/Starlette Gzip middleware

### ISSUE THREAD

**Issue by kevlarr** [erm/mangum#90] opened 2020-02-14 15:29 UTC
*(First off, awesome package. Being able to use an actual framework on Lambda without writing any 'transformation' code myself has been incredible.)*

I'm attempting to use Starlette's `GZipMiddleware` with FastAPI right now, and our front-end is sending a `accept-encoding: gzip, deflate, br` header.

When I configure the middleware like so...

```python
APP = FastAPI()
# ... other middleware
APP.add_middleware(
    GZipMiddleware,
    minimum_size=512,
)
HANDLER = Mangum(APP, enable_lifespan=False)
```

... I receive the following error.

```  
Exception in ASGI application

Traceback (most recent call last):
  File "/var/task/mangum/protocols/http.py", line 39, in run
    await app(self.scope, self.receive, self.send)
  File "/var/task/fastapi/applications.py", line 142, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/var/task/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/var/task/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/var/task/starlette/responses.py", line 200, in __call__
    await send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/var/task/starlette/middleware/errors.py", line 153, in _send
    await send(message)
  File "/var/task/mangum/protocols/http.py", line 97, in send
    self.response["body"] = body.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I had initially thought it might be due to the `minimum_size` parameter but removing that did not work. If I removed the middleware *completely* then my Lambda works perfectly fine.

I'm a little confused by the `"body": b""` part, since this Lambda *is* returning data, and when I test locally running the same `APP` with `uvicorn` I have no issues - body is compressed and status code is 200.

Is there something I need to do to configure Mangum for compression? Am I reading the stack trace wrong?

**
FastAPI 0.48.0
Mangum 0.7.0
Python 3.6.8

**Comment by erm** [comment] 2020-02-23 02:45
I think this is related to binary response support in AWS - might need to add some handling around the content-type (or this is possibly related to configuration, not sure at this point), so that it can return the encoded response. Relevant docs [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html).

Can you paste an example of the AWS event?

**Comment by lsorber** [comment] 2020-03-13 20:53
This is a great resource to troubleshoot this: https://github.com/activescott/apigateway-lambda-binary-response

**Comment by burritoIand** [comment] 2020-03-16 22:08
hey, I just hit this exact same error when trying to enable the Starlette GZip middleware on my app that's behind apigateway/cloudfront...

**Comment by erm** [comment] 2020-03-17 06:14
@burritoIand Currently gzip is not handled properly in Mangum - there is an open PR [here](https://github.com/erm/mangum/pull/93) around resolving the current binary response issues. Once these fixes are merged in I will push a release to resolve this.

**Comment by burritoIand** [comment] 2020-03-17 16:15
@erm ok I tried out that PR and it didn't work for me

**Comment by lsorber** [comment] 2020-03-17 16:49
@burritoIand What error did you see when you tried out the PR?

**Comment by erm** [comment] 2020-03-19 10:09
> Should Mangum handle it or do should it be handled elsewhere?

@burritoIand do you mean handle the configuration or handle the response? We want Mangum to handle gzip responses, but any specific deploy/build configuration should be handled elsewhere. 

What issues did you run into using @lsorber's PR? I haven't had a chance to review/test it yet, but it looks like the path forward here.

**Comment by burritoIand** [comment] 2020-03-19 18:56
@erm I meant handle the response, I'll try to revisit it today and report back!

**Comment by erm** [comment] 2020-03-23 13:02
@burritoIand I merged in @lsorber's PR, but I'm going to make sure the gzip responses are working/tested before I push the next release. Any additional details you could provide would be very helpful (especially an example AWS event or any error tracebacks).

**Comment by sses79** [comment] 2020-04-08 21:03
@erm 
Could you do a new release include @lsorber 's PR?

**Comment by erm** [comment] 2020-04-09 07:30
@sses79 sure, but I wanted to do some testing before I do - haven't had a chance yet. Have you had an issue with the current release that would be resolved by that PR? If I can reproduce an issue and test then it would be speed things up. 

Will try to push a release over the long weekend in any case.

**Comment by sses79** [comment] 2020-04-09 08:31
@erm 
The same error when I try to output an Apple .pkpass binary data (Content-Type application/vnd.apple.pkpass), I think that PR will fix body.decode() issue. 

File "/var/task/mangum/protocols/http.py", line 97, in send
    self.response["body"] = body.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Closed** 2020-04-12 06:15 UTC

**Comment by erm** [comment] 2020-04-12 06:18
Just released 0.7.5. This should resolve the gzip issues, and your issue @sses79 (see the README for including your content type in the `text_mime_types` list).

If there are any problems feel free to comment here and I'll reopen.

**Comment by sses79** [comment] 2020-04-14 08:28
Many thank :+1:

**Comment by burritoIand** [comment] 2020-04-25 18:16
@erm @lsorber just returned to this and tried out the latest release with gzip middleware enabled, it works! thank you! sorry I didn't test it earlier, been knee-deep in other stuff, cheers!
